config_version = 14

[bar.default]
capsule_radius = 2
center = []
color = "#A6ADC8"
concave_edge_corners = false
end = [ "tray", "notifications", "temp", "ram", "battery", "network", "volume", "clock" ]
font_family = "Ubuntu"
icon_color = "#A6ADC8"
margin_ends = 0
padding = 10
position = "bottom"
radius = 0
start = [ "launcher", "workspaces", "taskbar" ]
widget_spacing = 12

    [bar.default.dead_zone.actions]
    right = "none"
    scroll_down = "workspace-switch next"
    scroll_up = "workspace-switch prev"

[battery]
warning_threshold = 40

[control_center]
hidden_tabs = [ "media", "screen-time" ]

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "notification"

[dock]
active_monitor_only = true

[location]
address = "Cotabato City, Philippines"

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 959.9998779296875
    cy = 881.4998779296875
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
border = false
position = "bottom_center"

[osd]
border = false
position = "bottom_center"

[plugins]
enabled = []

[shell]
button_borders = false
card_borders = false
clipboard_history_max_entries = 500
corner_radius_scale = 0.20000000298023224
font_family = "Ubuntu"
input_borders = false
popup_borders = false
time_format = "{:%-I:%M %p}"

    [shell.animation]
    enabled = false
    speed = 2.0000000298023224

    [shell.launcher]
    categories = false
    compact = true
    show_app_origin_indicator = false
    sort_by_usage = false

        [shell.launcher.providers.emoji]
        global = false
        prefix = "e"

        [shell.launcher.providers.wallpaper]
        prefix = "w"

    [shell.panel]
    borders = false
    open_near_click_control_center = true
    wallpaper_position = "bottom_right"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Ayu"
custom_palette = "CatppuccinMochaBlue"
mode = "dark"
source = "custom"

    [theme.templates]
    enable_builtin_templates = false

[wallpaper]
directory = "/home/tjq/dotfiles/wallpapers"
transition = [ "disc" ]
transition_on_startup = true

    [wallpaper.automation]
    recursive = false

    [wallpaper.default]
    path = "/home/tjq/dotfiles/wallpapers/door.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/tjq/dotfiles/wallpapers/door.png"

[widget.battery]
show_label = true
label_content = "percent"

[widget.clock]
color = "#A6ADC8"
format = "|  {:%d %a} · {:%-I:%M %p}"

    [widget.clock.actions]
    left = "panel-toggle control-center home"

[widget.launcher]
scale = 1.4000000000000001

[widget.network]
show_label = false

[widget.ram]
show_value = true
stat = "ram_pct"

[widget.taskbar]
inactive_opacity = 0.80000000000000004
only_active_workspace = true
show_active_indicator = false
window_title_max_width = 32

[widget.temp]
show_value = true

[widget.volume]
show_label = false

[widget.workspaces]
active_pill_size = 1.5
empty_color = "surface"
focused_color = "outline"
occupied_color = "surface_variant"